### ISSUE TITLE
[Suggestion] Stone in Blast Furnace

### ISSUE THREAD

**Issue by Sar4h-3** [RubixDev/fabric-rug#15]
I think it would be really nice to be able to use a blast furnace to turn cobble into stone and stone into smooth stone. 
Compared to a Blast Furnace, a normal furnace ist just slow.
And who likes to wait ages for stone bricks when you dont have a smelter array?

**Comment by RubixDev** [comment]
I implemented it now, but I'm not sure if I get the release finished today

**Comment by RubixDev** [comment]
It's included in the new release
