### ISSUE TITLE
Load recipe-altering recipes before world load

### ISSUE THREAD

**Issue by Neubulae** [RubixDev/fabric-rug#17]
Loading Datapacks -> Loading World -> Loading Carpet config -> Reload

It's a bit redundant on server startups, tho that sounds like a hard issue

**Comment by RubixDev** [comment]
I would be able to move the recipe files in the correct location _before_ Minecraft reloads its resources for the first time, but Carpet Mod only parses the config file _after_ that, so at that point I don't know which recipes should be included and which don't. I could parse the important rules earlier myself to circumvent this, though that would be quite a lot of work and I'm not sure if it's even worth it at that point.

**Comment by Neubulae** [comment]
> I would be able to move the recipe files in the correct location _before_ Minecraft reloads its resources for the first time, but Carpet Mod only parses the config file _after_ that, so at that point I don't know which recipes should be included and which don't. I could parse the important rules earlier myself to circumvent this, though that would be quite a lot of work and I'm not sure if it's even worth it at that point.

I guess you could then do something as a quality-of-life improvement, like:
First time loading the config -> Dump the recipes to the correct location
then if the conf file is not changed and the recipes aren't altered, keep it as is, otherwise do it again?

**Comment by RubixDev** [comment]
Hi, sorry for not answering for so long. As you might have noticed I moved away to other projects.
Regarding your request I decided it is not worth it trying to get it to work, just for a cleaner and slightly faster start. I _might_ have another look sometime later though.
