### ISSUE TITLE
campSleeping doesn't appear to work

### ISSUE THREAD

**Issue by xEmberx** [RubixDev/fabric-rug#18]
Hey, I might just be doing something wrong, but I can't seem to enter the bed while sneaking.

**Comment by xEmberx** [comment]
Okay, I think I figured it out, I can't have anything in either of my hands to do it.  Possible bug?  Not sure, you're welcome to close if it's intentional.

**Comment by RubixDev** [comment]
Might be considered a bug. I already noticed that during testing, but didn't know any quick fix for it. I will have another look or at least add it to the description, so I'll leave this open for now.

**Comment by RubixDev** [comment]
Sorry, for leaving this open for so long. I moved away to other projects and lost interest in this project and in Minecraft in general.
I plan to work on the open issues in the next few days though, so hopefully I will get this fixed in the near future :)

**Comment by xEmberx** [comment]
No worries my man, you're entitled to your own interests :)
