### ISSUE TITLE
[Compat] edible items show AppleSkin food values while disabled

### ISSUE THREAD

**Issue by supersaiyansubtlety** [RubixDev/fabric-rug#19]
[AppleSkin](https://www.curseforge.com/minecraft/mc-mods/appleskin) displays food values for gold ingots, netherite scraps, slime balls, and magma cream, regardless of whether or not those items' `/carpet edibleX` rules are true.

**Comment by RubixDev** [comment]
Similar to #18 I already noticed this during testing, but didn't think much of it. I believe it has something to do with how I toggle them being edible, as I just add them as food items regardless of them being enabled, but then catch and cancel the eating action when the corresponding rule is disabled. I know this isn't a great solution, but the only one I could think of. I will try to come up with a fix in the next few days.

**Comment by RubixDev** [comment]
Sadly i wasn't able to get it to work. I tried fully setting the items to be edible and non-edible every time a rule is toggled and then reloading the server, however it appears such a resource reload doesn't reload the items and such the whole server would have to be restarted every time. I don't think it's too annoying though, as it only affects the players with Carpet, AppleSkin **and** Rug on their client anyways.
