### ISSUE TITLE
basaltToLavaConversion is not fully compatible with Carpet's movableBlockEntities

### ISSUE THREAD

**Issue by Infinidoge** [RubixDev/fabric-rug#24]
When using Carpet's `movableBlockEntities` in conjunction with Rug's `basaltToLavaConversion`, piston-pushed basalt does not correctly convert to lava.

Reproduced on Minecraft 1.16.5 with Rug 1.1.8, Carpet 1.4.43, and Fabric API 0.36.0

Setup: (Set `basaltToLavaConversion` and `movableBlockEntities` to `true`, Soul Soil is below the first basalt)
![image](https://user-images.githubusercontent.com/22727114/124685351-19443980-de9f-11eb-86a0-fdea31c09a94.png)

After pushing the button once: (Source block appears to be generated)
![image](https://user-images.githubusercontent.com/22727114/124685457-527ca980-de9f-11eb-931e-531e4f8483d7.png)

Right-clicking the apparent source block shows smoke particles, and can be done repeatedly. Right-clicking with a bucket appears to pick up lava, but attempting to place it reveals the empty bucket.

After pushing the button a second time: (Source block is revealed to not have generated)
![image](https://user-images.githubusercontent.com/22727114/124685497-63c5b600-de9f-11eb-85a4-d6976c165d40.png)

Changing `movableBlockEntities` to `false`, then repeating the steps, the lava generates, can be picked up with the bucket, and pressing the button repeatedly destroys the lava with the basalt block then generates a new lava source through the conversion.

Creating a direct lava generator setup:
![image](https://user-images.githubusercontent.com/22727114/124686085-7987ab00-dea0-11eb-9b60-c67e01ada94c.png)
Works as expected regardless of `movableBlockEntities`, though the lava generates twice before it stops generating. (Lava is able to be gotten with a bucket normally from both.

**Comment by RubixDev** [comment]
I can confirm both bugs you mentioned still working with the latest 1.17 versions. I will work on them now

**Comment by RubixDev** [comment]
**Finally got it!** The problem was, that carpet overrides one minecraft method, which I was changing for the basalt conversion, when `movableBlockEntities` is on, so I had to figure out a way to change that method the same way.

~Now onto that double conversion...~

**Comment by RubixDev** [comment]
Also what you said that it looks like it's working but isn't, that is only with rug installed on the client, or at least I didn't have it with a vanilla client

**Comment by RubixDev** [comment]
Got that as well now. It was basically just another basalt block generating, due to the vanilla behavior, that then immediately converted into lava again. I now added a check if the block already is a lava source, and if so, cancel the generation of the basalt block

**Comment by Infinidoge** [comment]
Nice! That was quick, good to see that it wasn't a deep incompatibility.
