### ISSUE TITLE
Backport to 1.15.2

### ISSUE THREAD

**Issue by justlukie** [RubixDev/fabric-rug#28]
Self explanatory

**Comment by RubixDev** [comment]
I didn't really plan to do any backports, as I don't see a reason to play in older versions, but I'll see what I can do

**Comment by justlukie** [comment]
Thanks so much

**Comment by RubixDev** [comment]
After thinking about it again, I will not do any backports to older versions or add new rules to previously supported versions. This project sadly already isn't much fun to maintain, so I don't want extra work for versions the majority of players don't use
