### ISSUE TITLE
[Feature Suggestion] ediblePhantomMembranes?

### ISSUE THREAD

**Issue by Decrepitdoors** [RubixDev/fabric-rug#33]
I was just thinking about this and how it could be a good addition with the other rules, I was thinking it could give you a few seconds of slow_falling?

**Comment by RubixDev** [comment]
Sounds good, I am currently doing a lot of other stuff though, so it might take a while

**Comment by RubixDev** [comment]
Sorry, but as I already had to remove the other edible rules in v1.2.1, I am still unable to get them working again, and they are quite stupid anyways, I won't add this feature unless I change my mind and get it working
