### ISSUE TITLE
Better easyHarvesting

### ISSUE THREAD

**Issue by ttrafford7** [RubixDev/fabric-rug#34]
1. Using a hoe on crops should damage hoe durability(+ Unbreaking support)
2. Fortune enchantment should work on a hoe to harvest more crops

**Comment by RubixDev** [comment]
Same as for #33 , it sounds good, but I am currently doing a lot of other stuff, so it might take a while

**Comment by RubixDev** [comment]
I don't think I will implement the second point, it seems a bit complex to do and isn't really part of `easyHarvesting` anymore
