### ISSUE TITLE
Multiple Issues with 1.18.2

### ISSUE THREAD

**Issue by QPCrummer** [RubixDev/fabric-rug#37]
First off, it doesn't launch in 1.18.2, giving this error:  https://pastebin.com/VH78WYzY

Secondly, the "Fluid Helper" seems to be totally mutilated by Mojang's tag changes. This is causing it not to build from source.

Thanks for you time reading this.

**Comment by RubixDev** [comment]
Got it all fixed up 98dca7cc8a08a79e9d5cee6bcca778b4ab137bb3
