### ISSUE TITLE
Port to 1.19

### ISSUE THREAD

**Issue by Zyax3** [RubixDev/fabric-rug#38]
I took a look at it and a part of the /peek command is broken with playermanager.createPlayer now needing a PublicPlayerKey but otherwise only the mappings need to be updated.

**Comment by RubixDev** [comment]
Sadly it's not only that, they changed the whole chat messaging stuff and switched from `java.util.Random` to their own `net.minecraft.util.math.random.Random`.

I will publish a 1.19 release later today
