### ISSUE TITLE
Rule EasyChest missing Mangrove 

### ISSUE THREAD

**Issue by MeeniMc** [RubixDev/fabric-rug#40]
Thanks for fixing the 'woodcutting' rule so quick. There are however other rules that need the Mangrove logs/planks added.

I found that Easychest does not work with Mangrove, presumably the following other ones also need verified: trapped chest, sticks, bark, itemframeactivatepressureplates?

**Comment by RubixDev** [comment]
The `itemFramesActivatePressurePlates` is already generic over all pressure plate blocks. I will release the fix for `easy[Chest, TrappedChest, Stick]Crafting` and `moreBarkCrafting` in a few minutes. Is there anything else missing?

Also thanks for finding these issues so quickly.
