### ISSUE TITLE
Failed to start server

### ISSUE THREAD

**Issue by micrwvae** [RubixDev/fabric-rug#42]
tried adding rug to my server 
first i used the 1.19.1 version but that showed in the logs
when i the switched to the 1.3.4 version for 1.19 the server failed to start up

https://bin.bloom.host/azihibikez

**Comment by RubixDev** [comment]
You are using incompatible Carpet/Rug versions. Please either upgrade Carpet and Rug (and potentially other mods) to the newest version supporting 1.19.1 (Carpet v1.4.83, Rug v1.3.5), or downgrade both to the last version, that supported 1.19 (Carpet v1.4.79, Rug v1.3.4).

There is no Rug version compatible with Carpet v1.4.80, which you are using.

**Comment by micrwvae** [comment]
tried upgrading carpet further but it also didnt start up 
downgrading to 4.79 worked thank you
