### ISSUE TITLE
Incompatible with Baritone

### ISSUE THREAD

**Issue by Greg-J** [RubixDev/fabric-rug#44]
Running a fresh install of Fabric 1.19.2 with 105 other mods and all is well, except for Baritone. If I have Rug installed and try to use Baritone, I get a bunch of "world" is null errors.

The errors start here: https://mclo.gs/8t8ZODJ#L2899

To find the issue I removed all mods and added them back one by on and it is `rug-1.19.1-1.3.7.jar` that causes this issue. Baritone operates normally without it.

I'm happy to upload my mods folder if that'll help you track it down as well.

**Comment by wagyourtail** [comment]
https://github.com/luisch444/ZickCarpet/pull/2
related. Same fix

**Comment by Greg-J** [comment]
Will there be a new release with this fix soon?

**Comment by RubixDev** [comment]
Sorry, I always left this open, because I somehow thought it would be a very complex issue, but I literally only had to change one line :sweat_smile:. The fix will be available in v1.4.0

(I only just realised that @wagyourtail already pointed that out, oops)
