### ISSUE TITLE
Rug preventing server from starting

### ISSUE THREAD

**Issue by LessThanBenji** [RubixDev/fabric-rug#46]
Hi, I'm using Rug 1.4.1 on Fabric 1.19.4 alongside Carpet 1.4.101, and the server throws this error whenever I attempt to launch it with (far as I can tell) any Rug parameter specified in carpet.conf.

[latest.log](https://github.com/RubixDev/Rug/files/11273996/latest.log)

Downgrading Rug to 1.4.0 has appeared to fix the issue for me.

**Comment by RubixDev** [comment]
This happened because you have your carpet config locked, but it should be fixed in v1.4.3

**Comment by LessThanBenji** [comment]
Amazing, thank you. Btw, is 1.4.3 still compatible with Minecraft 1.19.4?

**Comment by RubixDev** [comment]
I haven't tried, but very likely no

**Comment by LessThanBenji** [comment]
no problem, i'll just stick to 1.4.0 :) thanks!
