### ISSUE TITLE
Server startup crash

### ISSUE THREAD

**Issue by Aculoss** [RubixDev/fabric-rug#51]
[latest.log](https://github.com/RubixDev/Rug/files/13673281/latest.log)

EnderPearlEntity mixin and possible Carpet TCTC Addition incompatability.

**Comment by RubixDev** [comment]
Looks like an incompatibility with [Carpet Org Addition](https://modrinth.com/mod/carpet-org-addition) to me, specifically [this Redirect](https://github.com/cdqtzrc/Carpet-Org-Addition/blob/d2e54f96016b17608d373ea98a303b2705e9c29a/src/main/java/org/carpet_org_addition/mixin/rule/EnderPearlEntityMixin.java#L23-L29) conflicting with this one: https://github.com/RubixDev/Rug/blob/4da1e585afa8fe02454c94633b289ddc22173064/src/main/java/de/rubixdev/rug/mixins/EnderPearlEntityMixin.java#L13-L22 

I will work on this tomorrow

**Comment by RubixDev** [comment]
With v1.5.1 it should no longer crash, but the rules `enderPearlDamage` and `reachDistance` from Rug won't be usable when both mods are loaded as they conflict with `notDamageEnderPearl` and `maxBlockPlaceDistance` from Carpet Org Addition respectively.
