### ISSUE TITLE
zeroTickPlants not working (?)

### ISSUE THREAD

**Issue by wh0oo** [RubixDev/fabric-rug#53]
I was not able to confirm that zeroTickPlants is working as expected.  It is enabled by default.  I did see that it should work on sugar cane, because I found this:

https://github.com/RubixDev/Rug/blob/babfb607bc1c49009cea64b85c114275a4ab9917/src/main/java/de/rubixdev/rug/mixins/SugarCaneBlockMixin.java#L16-L33

I dont know what that means, i just saw a reference to both :)

Anyway, it doesnt work, if it is supposed to.  

<details>
<summary>mod list</summary>

```
BlockBot Api 1.0.0
BlockBot Discord 2.0.0-beta
BlossomLib 2.5.6+1.20.4
BlossomTpa 2.2.2+1.20.4
Carpet Mod 1.4.128+v231205
Carpet TIS Addition 1.54.4
Essential Addons 1.3.1
LuckPerms 5.4.113
MC Server Description 4.1.0+1.20.1
MixinExtras 0.3.2
Ordered Player List 0.1.3+1.20.2
Packet Tweaker 0.5.0+1.20.2-rc1
Placeholder API 2.3.0+1.20.3
Player Data API 0.4.0+1.20.3
Predicate API 0.3.0+1.20.2
Rotten Flesh to Leather 1.0.0
Rug 1.5.1
Server Translations API 2.2.0+1.20.3-rc1
SignLogger 0.0.1-betav1-1.20+
Styled Player List 3.3.0+1.20.3
atomicfu-jvm 0.23.1
conditional mixin 0.4.1
core 3.6.7
jaxb-api 2.2.4
kotlin-reflect 1.9.21
kotlin-stdlib 1.9.21
kotlin-stdlib-jdk7 1.9.21
kotlin-stdlib-jdk8 1.9.21
kotlinx-coroutines-core-jvm 1.7.3
kotlinx-coroutines-jdk8 1.7.3
kotlinx-datetime-jvm 0.4.1
kotlinx-serialization-cbor-jvm 1.6.2
kotlinx-serialization-core-jvm 1.6.2
kotlinx-serialization-json-jvm 1.6.2
sgui 1.3.0+1.20.2
snakeyaml 1.28
sqlite-jdbc 3.44.0.0
toml 3.6.7
```

</details>

I am happy to provide more info, but since Im not 100% positive, Ill wait..

**Comment by RubixDev** [comment]
I just tested it locally and zero ticking sugar cane works as expected in all 1.20.x versions, so either your contraption you used for testing is incorrect or there is some incompatibility with one of the other mods.

> It is enabled by default.
wdym? The rule's default value is `false` to keep the vanilla behaviour.

Could you please provide your full log file? (either here or on Discord)

**Comment by RubixDev** [comment]
For future reference: this was caused by user error. The feature worked as intended, it was just used incorrectly :shrug:
