### ISSUE TITLE
Potential Conflict? Fabric 1.19.2

### ISSUE THREAD

**Issue by DemonSlayer112** [RubixDev/fabric-rug#57]
I don't understand much of the logs, but i beleive its partly to do with some of the carpet mods i have, started since installing rug on my pack.

To give an brief explanition, the client loads and you can make a new world and join it, or join a pre existing world.
But if you leave a world back to main menu and try to rejoin it will crash for some reason.

Again, if you get to title, close client, reopen, rejoining doesnt crash, only when you try to rejoin, quite odd.
[latest.log](https://github.com/RubixDev/Rug/files/14891994/latest.log)
[crash-2024-04-05_18.02.41-server.txt](https://github.com/RubixDev/Rug/files/14891995/crash-2024-04-05_18.02.41-server.txt)

**Comment by RubixDev** [comment]
Haven't tested this yet, but I also don't support 1.19 anymore

**Comment by RubixDev** [comment]
This shouldn't be a problem in the upcoming 1.6.0 release anymore because the relevant code has been replaced by using BRRP.
