### ISSUE TITLE
Update to 1.21 Please

### ISSUE THREAD

**Issue by sternschnaube** [RubixDev/fabric-rug#58]

**Comment by RubixDev** [comment]
I'll just paste a message from my Discord here:

> yes I will, but it will probably still take some time. for the past few weeks i've been really busy with real life stuff like coming back to germany and now searching for an apartment, so I haven't had time to program recently. Apart from that, I still need to update both EnchantedShulkers and Inventorio to 1.20.5/1.20.6 and EnchantedShulkers has more priority for me there. And then for the 1.21 updates I will probably also start with Rug and CarpetGamerules again, as they are usually quicker and easier to update, and then move on to EnchantedShulkers and finally Inventorio. So I hope I'll get to it eventually, but it'll likely still take a while.

original message: https://discord.com/channels/1184774025185079397/1214512216980717619/1253435391638507711 sent on June 20.

**Comment by venaminecraft** [comment]
Thanks, sounds good 😄
